### ISSUE TITLE
Migrate Lock Threads to GitHub Actions

### ISSUE THREAD

**Issue by dessant** [babel/babel#11150]
Hi folks, [Lock Threads](https://github.com/dessant/lock-threads) is now a GitHub Action. Please move to the new workflow when you find the time, the GitHub App instance will be shut down this summer.

You can migrate by deleting `.github/lock.yml` and adding `.github/workflows/lock.yml` with the following content:

```yaml
name: 'Lock threads'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-inactive-days: '91'
          issue-lock-labels: 'outdated'
          pr-lock-inactive-days: '91'
          pr-lock-labels: 'outdated'
```

Once merged, you can uninstall the GitHub App from the organization and revoke its access.
