### ISSUE TITLE
[Bug]:  @babel/parser@7.14.8 breaks IstanbulJS skip logic

### ISSUE THREAD

**Issue by bcoe** [babel/babel#13750]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

There are unit tests in Istanbul that test the following syntax, and ensure that the else statement is removed from coverage tracking when an ignore comment is added:

```js
  if (args[0] === 1) {
    output = '1';
  } /* istanbul ignore else */ else if (args[0] === 2) {
    output = '2';
  } else if (args[0] === 3) {
    output = '3';
  } else {
    output = 'other';
  }
```

## Current behavior

IstanbulJS has stopped parsing ignore comments for else blocks.

## Expected behavior

IstanbulJS continues handling ignore comments.

### Environment

-  npm i @babel/parser@>=7.14.8

### Additional context

My hunch is that the refactor [here](https://github.com/babel/babel/pull/13521) changed how comments attach to `else` nodes, resulting in Istanbul's visitor no longer working.

The code that visits comments and skips the subsequent node can be found [here](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/src/visitor.js#L408).

I'm betting the visitor needs to be updated slightly to match @JLHwung's overhaul, but could use some help getting on the right track.

**Comment by nicolo-ribaudo** [comment]
Technically there isn't a "correct" way to attach comments, but I'm marking this as a regression for now since istanbul a big Babel consumer.

**Comment by bcoe** [comment]
@nicolo-ribaudo I updated the tests to pass with the new behavior, with the old behavior in comments.

Reading the prior behavior, it seems that it was expected that coverage would stop being counted from the else statement forward (the old behavior seems slightly weird to me too, I don't understand why it would be expected that line 3 and 4 are in the coverage table):

```yaml
name: ignore chained else
code: |
  if (args[0] === 1) {
    output = '1';
  } /* istanbul ignore else */ else if (args[0] === 2) {
    output = '2';
  } else if (args[0] === 3) {
    output = '3';
  } else {
    output = 'other';
  }
tests:
  - name: '1'
    args: [1]
    out: '1'
    # Refs: https://github.com/babel/babel/issues/13750
    # lines: {'1': 1, '2': 1, '3': 0, '4': 0}
    lines: {'1': 1, '2': 1, '3': 0, '4': 0, '5': 0, '6': 0, '8': 0}
    # Refs: https://github.com/babel/babel/issues/13750
    # branches: {'0': [1, 0], 1: [0]}
    branches: {'0': [1, 0], 1: [0, 0], 2: [0, 0]}
    # Refs: https://github.com/babel/babel/issues/13750
    # statements: {'0': 1, '1': 1, '2': 0, '3': 0}
    statements: {'0': 1, '1': 1, '2': 0, '3': 0, '4': 0, '5': 0, '6': 0}
  - name: '2'
    args: [2]
    out: '2'
    # Refs: https://github.com/babel/babel/issues/13750
    # lines: {'1': 1, '2': 0, '3': 1, '4': 1}
    lines: {'1': 1, '2': 0, '3': 1, '4': 1, '5': 0, '6': 0, '8': 0}
    # Refs: https://github.com/babel/babel/issues/13750
    # branches: {'0': [0, 1], 1: [1]}
    branches: {'0': [0, 1], 1: [1, 0], 2: [0, 0]}
    # Refs: https://github.com/babel/babel/issues/13750
    # statements: {'0': 1, '1': 0, '2': 1, '3': 1}
    statements: {'0': 1, '1': 0, '2': 1, '3': 1, '4': 0, '5': 0, '6': 0}
  - name: '3'
    args: [3]
    out: '3'
    # Refs: https://github.com/babel/babel/issues/13750
    # lines: {'1': 1, '2': 0, '3': 1, '4': 0}
    lines: {'1': 1, '2': 0, '3': 1, '4': 0, '5': 1, '6': 1, '8': 0}
    # Refs: https://github.com/babel/babel/issues/13750
    # branches: {'0': [0, 1], 1: [0]}
    branches: {'0': [0, 1], 1: [0, 1], 2: [1, 0]}
    # Refs: https://github.com/babel/babel/issues/13750
    # statements: {'0': 1, '1': 0, '2': 1, '3': 0}
    statements: {'0': 1, '1': 0, '2': 1, '3': 0, '4': 1, '5': 1, '6': 0}
````

and:

```yaml
name: ignore in complex logical expression
code: >
  if (args[0] === 1  || /* istanbul ignore next */ (args[0] === 2  || args[0] === 3)) {
     output = args[0] + 10;
  } else {
     output = 20;
  }
tests:
  - args: [1]
    out: 11
    lines: {'1': 1, '2': 1, '4': 0}
    # Refs: https://github.com/babel/babel/issues/13750
    # branches: {'0': [1, 0], '1': [1]}
    branches: {'0': [1, 0], '1': [1, 0, 0]}
    statements: {'0': 1, '1': 1, '2': 0}
```

* `lines`: representing lines in the source.
* `branches`: representing distinct logical paths in `if`, `||`, etc.
* `statements`: e.g., `output = '1';`, they are similar to `lines` but will have a start and end position associated with them.

**Comment by nicolo-ribaudo** [comment]
I'm inclined to consider this as a bugfix and not as a regression.

Consider this input code:
```js
if (A) { B; } else if (C) { D; } else { E; }
```

We can mark some AST nodes relevant to this bug:
```
if (A) { B;     } else if (C) { D; } else { E; }
       ^^^^^^^^^^      ^^^^^^^^^^^^^^^^^^^^^^^^^
       First if's       Second if statement, or
       consequent        first if's alternate

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                First if statement
```

We can now add that `/* istanbul ignore else */` comment to our code:
```
if (A) { B;     } /* comment */ else if (C) { D; } else { E; }
       ^^^^^^^^^^                    ^^^^^^^^^^^^^^^^^^^^^^^^^
       First if's                     Second if statement, or
       consequent                      first if's alternate

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                First if statement
```

As you can see, the comment doesn't "touch" the second `if` statement. We could attach it to the AST in two places:
- as a trailing comment of _First if's consequent_
- as an inner comment of _First if statement_

We give precedence to trailing/leading comments, since it's a more specific indication than a generic "inner comment". You can verify [on ASTExplorer](https://astexplorer.net/#/gist/f30292121e1840335302eac30155048e/latest) that in your example the comment is attached as a trailing comment of that block statement.

For some reason, pre-7.14.8 Babel was attaching that comment as a leading comment of _Second if statement_, as if you had this input code:
```
if (A) { B;     } else /* comment */ if (C) { D; } else { E; }
       ^^^^^^^^^^                    ^^^^^^^^^^^^^^^^^^^^^^^^^
       First if's                     Second if statement, or
       consequent                      first if's alternate

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                First if statement
```
or
```js
if (args[0] === 1) {
  output = '1';
} else /* istanbul ignore else */ if (args[0] === 2) {
  output = '2';
} else if (args[0] === 3) {
  output = '3';
} else {
  output = 'other';
}
```

I admit that your fixtures are too cryptic for me to understand (or maybe I could, but it's 11pm here and I'm tired :grimacing:), but looking ad the AST and at your visitor I _think_ that pre-7.14.8 the ignored lines were only these:
```js
if (args[0] === 1) {
  output = '1';
} else if (args[0] === 2) {
  output = '2';
} else if (args[0] === 3) { // <-- ignored
  output = '3';             // <-- ignored
} else {                    // <-- ignored
  output = 'other';         // <-- ignored
}                           // <-- ignored
```

if it's true (if it's not, please correct me), as an InstanbulJS user I would find the old behavior surprising: why isn't it also also ignoring the `if (args[0] === 2)` branch? The fixed comment attachment forces me to write either
```js
if (args[0] === 1) {
  output = '1';
} else /* istanbul ignore else */ if (args[0] === 2) {
  output = '2';
} else if (args[0] === 3) {
  output = '3';
} else {
  output = 'other';
}
```
or
```js
/* istanbul ignore else */
if (args[0] === 1) {
  output = '1';
} else if (args[0] === 2) {
  output = '2';
} else if (args[0] === 3) {
  output = '3';
} else {
  output = 'other';
}
```
making it more clear (imo) which `if` statement's `else` branch should be ignored.

**Comment by bcoe** [comment]
@nicolo-ribaudo you're right, testing this behavior things to work as you imply:

```yml
name: ignore chained else
code: |
  /* istanbul ignore else */
  if (args[0] === 1) {
    output = '1';
  } else if (args[0] === 2) {
    output = '2';
  } else if (args[0] === 3) {
    output = '3';
  } else {
    output = 'other';
  }
tests:
  - name: '1'
    args: [1]
    out: '1'
    lines: {'2': 1, '3': 1}
    branches: {'0': [1]}
    statements: {'0': 1, '1': 1}
```

Also, to get the old behavior you can just refactor to this:

```yml
  if (args[0] === 1) {
    output = '1';
  } else /* istanbul ignore else */ if (args[0] === 2) {
    output = '2';
  } else if (args[0] === 3) {
    output = '3';
  } else {
    output = 'other';
  }
```

**Comment by bcoe** [comment]
Behavior of `if`/`else` seems reasonable 👍 

I'm a little confused by what's happening with `ignore next` for a logical expression:

```yml
name: ignore in complex logical expression
code: >
  if (args[0] === 1  || /* istanbul ignore next */ (args[0] === 2  || args[0] === 3)) {
     output = args[0] + 10;
  } else {
     output = 20;
  }
tests:
  - args: [1]
    out: 11
    lines: {'1': 1, '2': 1, '4': 0}
    # Refs: https://github.com/babel/babel/issues/13750
    # branches: {'0': [1, 0], '1': [1]}
    branches: {'0': [1, 0], '1': [1, 0, 0]}
    statements: {'0': 1, '1': 1, '2': 0}
```

In older versions of Istanbul I believe `/* istanbul ignore next */ (args[0] === 2  || args[0] === 3))` appropriately ignored the logical expression in the parenthesis.

I think the problem is similar where it's grouping the logical expression slightly differently, I can likely work around this if need be.

**Comment by JLHwung** [comment]
```js
if(/* istanbul ignore next */ (args[0] === 2 || args[0] === 3)) {}
```

In this example the LogicalExpression starts with `a`, the left parenthesis separates the comment from `LogicalExpression`, so the comment does not attach to the LogicalExpression, and because no AST node starts with `(`, it falls to the `innerComments` of upper AST structure, in this case, the `IfStatement`.

When `createParenthesizedExpressions` is enabled, a `ParethesizedExpression` starting with `(` is created, the comment now attaches to the `ParethesizedExpression` as a leading comment.

If you want the comment attaching to the LogicalExpression, the comment should immediately before the start of LogicalExpression. Note that the comment will be attached to the uppermost AST node that immediately follows the comment:

```js
if((/* istanbul ignore next */ args[0] === 2 || args[0] === 3)) {} // ignore LogicalExpression

if((/* istanbul ignore next */ args[0] === 2) || args[0] === 3) {} // ignore the first BinaryExpression
```

Before 7.14.8, a non-whitespace token (i.e. `(`) can appear between a leading comment and the attached AST node. After 7.14.8, only [comment whitespace](https://github.com/babel/babel/blob/main/packages/babel-parser/ast/comment-attachment.md#comment-whitespace) can exist between a leading comment and the attached AST node, with exception of trailing commas ([a bit messy to track](https://github.com/babel/babel/blob/9780c5667f0b1870b0015e668b900bdeece58672/packages/babel-parser/src/parser/comments.js#L156-L187))

We could allow leading/trailing comments to span across parenthesis, but it will complicate current handling logic and kill performance. Although we have `extra.parenStart`, it is not sufficient to support comments attaching spanning because `extra.parenStart` only records the outermost parenthesis:

```js
(/* 1 */(/* 2 */(/* 3* /a = 1)))
// Currently only `/* 3 */` attached to `a = 1`
// the other two comments are innerComments of ExpressionStatement
```

I lean to use the `createParenthesizedExpressions` option if you demand the comment should be attached to a parenthesized expression. After all, the comment attaching relies on the AST layout: The more granular the AST structure is, the more likely a non-whitespace token can be represented by an AST node, to which a comment can attach without being an inner comment of upper AST node.

**Comment by bcoe** [comment]
@JLHwung I played with `createParenthesizedExpressions` but it doesn't quite give the behavior I'd expect (I'd likely need to fiddle with the logic for applying comments to the AST). However, I'm a bit worried that adding these additional branches to the AST could hurt performance.

I played more, and I think your suggestion of moving the comment to inside the parenthesis is reasonable:

```yaml
name: ignore in complex logical expression
code: >
  if (args[0] === 1 || (/* istanbul ignore next */ args[0] === 2  || args[0] === 3)) {
     output = args[0] + 10;
  } else {
     output = 20;
  }
tests:
  - args: [1]
    out: 11
    lines: {'1': 1, '2': 1, '4': 0}
    branches: {'0': [1, 0], '1': [1]}
    statements: {'0': 1, '1': 1, '2': 0}
```

☝️ it's not too much trouble to have people move their comment as demonstrated above, and it solves problem of this new behavior without changing the parse too much.
