### ISSUE TITLE
[Bug]: Unable to run TypeScript using `babel-node`

### ISSUE THREAD

**Issue by LandonSchropp** [babel/babel#14218]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

``` ts
console.log("hello");
```

### Configuration file name

babel.config.json

### Configuration

``` json
{
  "presets": [
    "@babel/preset-typescript"
  ]
}
```

### Current and expected behavior

According to the [instructions for @babel/preset-typescript](https://babeljs.io/docs/en/babel-preset-typescript), `babel-node` needs to be run with the `--extensions` flag. Here's are a few of the commands I've tried to run my code:

``` bash
babel-node -x .ts example.ts
babel-node -x .ts -- example.ts
babel-node --extensions .ts index.ts
babel-node --extensions .ts -- index.ts
```

Each one of these commands produces the same error:

```
 -- example.ts
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/landon/Development/personal/wordle-solver/example.ts
    at new NodeError (node:internal/errors:371:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:87:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:102:38)
    at defaultLoad (node:internal/modules/esm/load:21:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v17.4.0
```

### Environment

``` yml
  System:
    OS: macOS 12.1
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
  npmPackages:
    @babel/cli: 7.16.8 => 7.16.8
    @babel/core: 7.16.12 => 7.16.12
    @babel/node: 7.16.8 => 7.16.8
    @babel/preset-env: 7.16.11 => 7.16.11
    @babel/preset-typescript: ^7.16.7 => 7.16.7
    @babel/register: 7.16.9 => 7.16.9
    eslint: 8.8.0 => 8.8.0
```

### Possible solution

It doesn't seem like the `-x` flag has any effect. Maybe the documentation needs to be updated?
