### ISSUE TITLE
Unknown option: direct.format

### ISSUE THREAD

**Issue by dudo** [babel/babel#2434]
https://github.com/brunch/brunch/issues/1018

I thought it might be an issue with brunch, but they pointed me over here. any ideas?

`Compiling of 'app/js/app.jsx' failed. [BABEL] app/js/app.jsx: Unknown option: direct.format`

I'm not sure if this is directly related to babel, or brunch, but if I could get some help setting up this app, that would be fantastic =)

**Comment by sebmck** [comment]
The error message is correct. There's no option called `format`. See the [option docs](https://babeljs.io/docs/usage/options/) for a full list of valid options.

**Comment by dudo** [comment]
https://babeljs.io/docs/setup/#brunch

```
plugins:
  babel:
    whitelist: ["arrowFunctions"]
    format:
      semicolons: false
```
Is that incorrect, then?
