### ISSUE TITLE
Run flow on latest version of node in CI

### ISSUE THREAD

**Issue by hzoo** [babel/babel#4710]
Basically the same as the eslint issue: https://github.com/babel/babel/issues/4638 and PR https://github.com/babel/babel/pull/4680

We should remove the comment https://github.com/gyandeeps/babel/blob/46615605a07fa92b926dd0ef35a52b7dda0e9fb4/Makefile#L49 too when it works.

so I would make a new env variable like `FLOW` and run `./node_modules/.bin/flow check` instead of eslint for LINT

```
script: 
  - 'if [ -n "${LINT-}" ]; then make lint ; fi'
  - 'if [ -z "${LINT-}" ]; then make test-ci ; fi'

matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: LINT=true
```
