### ISSUE TITLE
Add support for .babelrc.yaml

### ISSUE THREAD

**Issue by gajus** [babel/babel#4980]
This is an alternative proposal to https://github.com/babel/babel/pull/4892 ("Add support for .babelrc.js files").

> tl;dr;
>
> Using YAML format can achieve anywhere from 30% to +50% reduction (lines code code) of the configuration length without compromising readability.
>
> In contrast to using JavaScript as a configuration format, using YAML format restricts complexity of the document to the use of [merge and anchor](#merge-and-anchor) features.

I am worried that adding configuration support in JavaScript format will lead to complex configurations that are hard to read. A case in point is webpack. webpack configurations have a tendency to grow in size out of proportion, include an exceeding amount of conditional checks and merging logic.

With no disrespect to the author of the following code example, consider this configuration:

* [https://github.com/davezuko/react-redux-starter-kit/blob/master/config/webpack.config.js](https://github.com/davezuko/react-redux-starter-kit/blob/2675bb29115b44c3fb077e7359fd88d5e2989d0e/config/webpack.config.js)

In the above configuration:

* [There is string concatenation](https://github.com/davezuko/react-redux-starter-kit/blob/2675bb29115b44c3fb077e7359fd88d5e2989d0e/config/webpack.config.js#L31)
* [Conditional setting using `__TEST__` variable](https://github.com/davezuko/react-redux-starter-kit/blob/2675bb29115b44c3fb077e7359fd88d5e2989d0e/config/webpack.config.js#L72)
* [Conditional setting using `__DEV__` variable](https://github.com/davezuko/react-redux-starter-kit/blob/2675bb29115b44c3fb077e7359fd88d5e2989d0e/config/webpack.config.js#L86)
* [Conditional setting using `__PROD__` variable](https://github.com/davezuko/react-redux-starter-kit/blob/2675bb29115b44c3fb077e7359fd88d5e2989d0e/config/webpack.config.js#L92)
* [Filtering logic](https://github.com/davezuko/react-redux-starter-kit/blob/2675bb29115b44c3fb077e7359fd88d5e2989d0e/config/webpack.config.js#L200)

In short, there is no way see whats the resulting configuration without executing the code.

> I understand that webpack and Babel face different challenges.
>
> However, it is not unreasonable to think that similar patterns will emerge in Babel if configuration in JavaScript format is supported.

However, I do see an issue of repetition in `.babelrc`.

Lets use this configuration as an example:

```json5
{
  "env": {
    "test": {
      // "ava" requires "transform-es2015-modules-commonjs"
      "plugins": [
        "istanbul",
        "transform-es2015-modules-commonjs",
        "transform-export-default-name",
        "transform-flow-strip-types",
        "transform-async-to-generator",
        "transform-es2015-destructuring",
        "transform-es2015-parameters",
        [
          "transform-object-rest-spread",
          {
            "useBuiltIns": true
          }
        ],
        "transform-class-properties"
      ],
      "sourceMaps": "inline"
    },
    // Used for debugging the application in modern browsers.
    "development": {
      "plugins": [
        "transform-export-default-name",
        "transform-flow-strip-types",
        "transform-es2015-destructuring",
        "transform-es2015-parameters",
        [
          "transform-object-rest-spread",
          {
            "useBuiltIns": true
          }
        ],
        "transform-class-properties"
      ]
    },
    // Used for modern browsers that support generators.
    "production-mainstream": {
      "plugins": [
        "closure-elimination",
        "transform-flow-strip-types",
        "transform-async-to-generator",
        "transform-es2015-destructuring",
        "transform-es2015-parameters",
        [
          "transform-object-rest-spread",
          {
            "useBuiltIns": true
          }
        ],
        "transform-class-properties",
        "transform-es2015-classes"
      ]
    },
    // Used for legacy browser support.
    "production-legacy": {
      "plugins": [
        "transform-flow-strip-types"
      ],
      "presets": [
        "es2015",
        "stage-0"
      ]
    }
  }
}

```

This is a long configuration that shares a lot in common. I cannot use `plugins` in the general scope because plugin order is important.

First, lets start by rewriting the above configuration using YAML:

<a name="merge-and-anchor" />

> Note:
> For those not familiar with YAML, I recommend read through this cheatsheet.
> https://learnxinyminutes.com/docs/yaml/

```yaml
---
env:
  # "ava" requires "transform-es2015-modules-commonjs"
  test:
    plugins:
      - istanbul
      - transform-es2015-modules-commonjs
      - transform-export-default-name
      - transform-flow-strip-types
      - transform-async-to-generator
      - transform-es2015-destructuring
      - transform-es2015-parameters
      - 
        - transform-object-rest-spread
        - useBuiltIns: true
      - transform-class-properties
    sourceMaps: inline
  # Used for debugging the application in modern browsers.
  development:
    plugins:
      - transform-export-default-name
      - transform-flow-strip-types
      - transform-es2015-destructuring
      - transform-es2015-parameters
      - 
        - transform-object-rest-spread
        - useBuiltIns: true
      - transform-class-properties
   # Used for modern browsers that support generators.
  production-mainstream:
     plugins:
      - closure-elimination
      - transform-flow-strip-types
      - transform-async-to-generator
      - transform-es2015-destructuring
      - transform-es2015-parameters
      - 
        - transform-object-rest-spread
        - useBuiltIns: true
      - transform-class-properties
      - transform-es2015-classes
   # Used for legacy browser support.
  production-legacy:
     plugins:
       - transform-flow-strip-types
     presets:
       - es2015
       - stage-0

```

Thats already a reduction from 68 lines of code to 48 (30% reduction). However, we can do better.

YAML format supports [merge](http://yaml.org/type/merge.html) key. Using merge and anchoring, we can rewrite the above configuration as:

```yaml
---
aliases:
  common: &common
    - transform-flow-strip-types
    - transform-export-default-name
    - transform-es2015-destructuring
    - transform-es2015-parameters
    - 
      - transform-object-rest-spread
      - useBuiltIns: true
    - transform-class-properties
env:
  # "ava" requires "transform-es2015-modules-commonjs"
  test:
    plugins:
      - istanbul
      - transform-es2015-modules-commonjs
      - transform-async-to-generator
      - *common
    sourceMaps: inline
  # Used for debugging the application in modern browsers.
  development:
    plugins:
      - transform-export-default-name
      - *common
  # Used for modern browsers that support generators.
  production-mainstream:
    plugins:
      - closure-elimination
      - transform-async-to-generator
      - *common
      - transform-es2015-classes
  # Used for legacy browser support.
  production-legacy:
     plugins:
       - transform-flow-strip-types
     presets:
       - es2015
       - stage-0
```

> Note:
> There is a gotcha. The above example creates a list within a list. Therefore, a special rule would need to be added that flattens the configuration.

Thats a reduction from 68 lines of code to 38 (45% reduction).

The most import thing here is not reduction of lines though, but reduction of repeated content thats shared across multiple configurations.

One of the most common mistakes that I make when configuring multiple environments, is forgetting to add some configuration to one of the configs that needs to be shared across a group of configurations. Using YAML solves this issue.

In contrast to allowing JavaScript configuration files, YAML configuration files introduce a set level of complexity.
